# .gitcliff.toml

##commit prefixes:
#feat: new schema check
#fix: wheel missing pshell files
#docs: add SQL Server 2016 note
#chore: bump version

[changelog]
header = "# Changelog"
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}{% else %}## [Unreleased]{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}{% if commit.links %} {{ commit.links | join(sep=" ") }}{% endif %}
{% endfor %}
{% endfor %}
"""
footer = ""

[git]
# generate notes since the previous tag
conventional_commits = true
filter_unconventional = false
split_commits = true
tag_pattern = "v[0-9]*"
# map types to groups
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^docs", group = "Docs" },
  { message = "^refactor", group = "Changed" },
  { message = "^perf", group = "Changed" },
  { message = "^chore", group = "Chore" },
  { message = "^test", group = "Tests" },
]
