site_name: "CSC API Dataflow"

theme:
  name: material
  logo: assets/images/d2ilogo.png
  localization:
    toc: "Page Sections" 
  palette:
    primary: blue
    accent: light-blue
  features:
    # - navigation.tabs       # swap to tabs in ribbon (depreciated)
    - navigation.top          # shift TOC into left sidebar
    - navigation.sections     # highlight current section during scroll
    - tasklist                # checklist boxes in dev planning

  toc:
    depth: 3  # (alter if h-depth deepens beyond h3. Current : H1, H2, H3)
nav:
  - Overview: index.md
  - Stakeholders: stakeholders.md
  - System Requirements: system_requirements.md
  - 1 Deploy SSD: 1_deploy_ssd.md
  - 2 Test API: 2_test_api.md
  - 3 API Configuration: 3_api_config.md
  - 4 Deploy API: 4_deploy_api.md
  - JSON Structure: payload_structure.md
  - Development Plan: development_plan.md
plugins:
  - search
  - pdf-export
  - mermaid2  # enable Mermaid diagram

extra_css:
  - assets/css/styles.css
extra_javascript:
  - assets/js/scripts.js
