site_name: "DfE CSC API Dataflow"
theme:
  name: material
  logo: assets/images/d2ilogo.png
nav:
  - Overview: index.md
  - Stakeholders: stakeholders.md
  - Configuration and Setup: setup.md
  - API Usage: api_usage.md
plugins:
  - search
  - pdf-export

extra_css:
  - assets/css/styles.css
