site_name: "CSC SSD API Dataflow"
site_url: "https://data-to-insight.github.io/csc_api_data_collection/"
site_author: " "  

theme:
  name: material # installed themes are: material, mkdocs, readthedocs
  logo: assets/images/d2ilogo.png
  localization:
    toc: "Page Sections" 
  palette:
    primary: blue
    accent: light-blue
  features:
    - navigation.top          # shift TOC into left sidebar
    - navigation.sections     # highlight current section during scroll
    - tasklist                # checklist boxes in dev planning
    - content.tables.sort     # Table sorting
    - content.code.fences  # make sure fenced code is rendered correctly

    # - navigation.tabs       # swap to tabs in ribbon (depreciated)
    # - content.pdf             #  Enable the PDF button    
  toc:
    depth: 3  # (alter if h-depth deepens beyond h3. Current : H1, H2, H3)


# comment out if wanting export pdf subset of sections
nav: 
  - Project Overview: index.md

  - 🟧 Local Authority Guidance:
      - System & Access Requirements: system_requirements.md
      - LA Deployment Roadmap: roadmap_la_deployment.md  
  - 🟧 SSD Deployment:
      - SSD Schema: deploy_ssd_schema.md
  - 🟧 API Deployment:
      - API Download : release.md
      - API Deployment (Python): api_python_deployment.md
      - API Deployment (PShell): api_powershell_deployment.md
      - API Configuration: api_config.md
      - API Testing: test_api.md
      - JSON Payload Structure: json_payload_structure.md
      - Data Security: data_security.md
      - Troubleshooting & FAQ: troubleshooting_faq.md

  # - Stakeholders: stakeholders.md

  - 🟧 Development:
      - Implementation Roadmap: roadmap_implementation.md
      # - Feature Backlog: feature_backlog.md

  - 🟧 Admin:
      - Release Process: admin-release_process.md
      - Actions Workflows: admin-actions_workflow_overview.md
      - CLI Interface: admin-cli_interface.md


plugins:
  - search
  - mermaid2: # retain as pymdownx.superfences not displaying mermaid
      arguments:
        securityLevel: loose
  - with-pdf:
      output_path: "pdf/csc_ssd_api_documentation.pdf"
      cover: true
      cover_title: "CSC SSD API Documentation"
      cover_subtitle: "Data to Insight | Deployment Reference Guide [ver:0.3.4 - spec:0.8] [DRAFT]"
      copyright: " "
      # pages: ""
      # exclude_docs: ""
      # draft_docs:""
      # not_in_nav:""

markdown_extensions:
  # mermaid + fenced content
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  #- pymdownx.superfences
  # include partials from docs/_partials
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs


extra_css: 
  - assets/css/styles.css
extra_javascript:
  - assets/js/scripts.js
  - assets/js/colourCells.js # dev plan cell status colouration
  - assets/js/tables.js # sorting on dev plan table(s)


extra_templates:
  - overrides/pdf/default.html.j2
extra:
  site_author: "D2I"
  copyright: "© 2025"
