site_name: "CSC SSD API Dataflow"
site_url: "https://data-to-insight.github.io/csc_api_data_collection/"
site_author: " "  

theme:
  name: material # installed themes are: material, mkdocs, readthedocs
  logo: assets/images/d2ilogo.png
  localization:
    toc: "Page Sections" 
  palette:
    primary: blue
    accent: light-blue
  features:
    - navigation.top          # shift TOC into left sidebar
    - navigation.sections     # highlight current section during scroll
    - tasklist                # checklist boxes in dev planning
    - content.tables.sort     # Table sorting

    # - navigation.tabs       # swap to tabs in ribbon (depreciated)
    # - content.pdf             #  Enable the PDF button    
  toc:
    depth: 3  # (alter if h-depth deepens beyond h3. Current : H1, H2, H3)

nav:
# comment out here if wanting export pdf of subset of sections (or reduced front-end published)
  - Overview: index.md
  - System Requirements: system_requirements.md
  - Deploy SSD: deploy_ssd.md
  - API Config: api_config.md
  - API Test: test_api.md
  - API Deploy: deploy_api.md
  - JSON Structure: payload_structure.md
  - Troubleshoot & FAQ: troubleshooting_faq.md
  # - Stakeholders: stakeholders.md
  - Dev Plan: development_plan.md
  - Dev Backlog: git_dev_backlog.md


plugins:
  - search
  - mermaid2 # removed as adding table sorting via pymdownx.superfences
  - with-pdf:
      output_path: "pdf/csc_ssd_api_documentation.pdf"
      cover: true
      cover_title: "CSC SSD API Documentation"
      cover_subtitle: "Data to Insight | Deployment Guide [ver:0.3.3 - spec:0.7] [DRAFT]"
      copyright: " "
      # pages: ""
      # exclude_docs: ""
      # draft_docs:""
      # not_in_nav:""


extra_css: 
  - assets/css/styles.css
extra_javascript:
  - assets/js/scripts.js
  - assets/js/colourCells.js # dev plan cell status colouration
  - assets/js/tables.js # sorting on dev plan table(s)
extra_templates:
  - overrides/pdf/default.html.j2
extra:
  site_author: "D2I"
  copyright: "© 2025"
