name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', if that is your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin mkdocs-with-pdf

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
